apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: secret-container
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-credentials
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-credentials
                  key: password
      imagePullSecrets:
        - name: registry-secret