apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: time-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: time-container
              image: busybox
              command: ["sh", "-c", "date"]
          restartPolicy: OnFailure