apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  redis-username: cm9vdA==       # base64 encoded value of "root"
  redis-password: cGFzc3dvcmQ=   # base64 encoded value of "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: redis-password