apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deployment
  labels:
    app: random-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-app
  template:
    metadata:
      labels:
        app: random-app
    spec:
      containers:
        - name: random-container
          image: random-image:latest
          ports:
            - containerPort: 8080